# Note: this is only a partial configuration

scrape_configs:

  - job_name: 'imap-mailboxes'
    scheme: http
    metrics_path: /probe
    static_configs:
    - targets:
      - INBOX
      labels:
        username: 'info@example.com'
        hostname: 'imap.example.com'

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_mailbox
      - source_labels: [username]
        target_label: __param_username
      - source_labels: [hostname]
        target_label: __param_hostname
      - source_labels: [__param_mailbox]
        target_label: mailbox
      - target_label: __address__
        replacement: imap-mailbox-exporter:9101
