name: "CI"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.18.0'

    - name: Install dependencies
      run: |
        go version
        go install golang.org/x/lint/golint@latest
    - name: Build
      run: go build .

    - name: Run Vet & Lint
      run: |
        go vet .
        golint -set_exit_status=1 .